/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NeighbourhoodsIndexRouteImport } from './routes/neighbourhoods.index'
import { Route as NeighbourhoodsIdRouteImport } from './routes/neighbourhoods.$id'

const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighbourhoodsIndexRoute = NeighbourhoodsIndexRouteImport.update({
  id: '/neighbourhoods/',
  path: '/neighbourhoods/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighbourhoodsIdRoute = NeighbourhoodsIdRouteImport.update({
  id: '/neighbourhoods/$id',
  path: '/neighbourhoods/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/neighbourhoods/$id': typeof NeighbourhoodsIdRoute
  '/neighbourhoods/': typeof NeighbourhoodsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/neighbourhoods/$id': typeof NeighbourhoodsIdRoute
  '/neighbourhoods': typeof NeighbourhoodsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/neighbourhoods/$id': typeof NeighbourhoodsIdRoute
  '/neighbourhoods/': typeof NeighbourhoodsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compare' | '/neighbourhoods/$id' | '/neighbourhoods/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/neighbourhoods/$id' | '/neighbourhoods'
  id: '__root__' | '/' | '/compare' | '/neighbourhoods/$id' | '/neighbourhoods/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  NeighbourhoodsIdRoute: typeof NeighbourhoodsIdRoute
  NeighbourhoodsIndexRoute: typeof NeighbourhoodsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhoods/': {
      id: '/neighbourhoods/'
      path: '/neighbourhoods'
      fullPath: '/neighbourhoods/'
      preLoaderRoute: typeof NeighbourhoodsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighbourhoods/$id': {
      id: '/neighbourhoods/$id'
      path: '/neighbourhoods/$id'
      fullPath: '/neighbourhoods/$id'
      preLoaderRoute: typeof NeighbourhoodsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  NeighbourhoodsIdRoute: NeighbourhoodsIdRoute,
  NeighbourhoodsIndexRoute: NeighbourhoodsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
